import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalStyle } from "./global";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flimed - Kids",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
      <GlobalStyle/>
    </html>
  );
}
